# Generated by Django 2.2.5 on 2019-10-03 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['handling', 'posted']},
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['handling', 'posted']},
        ),
        migrations.AlterModelOptions(
            name='handling',
            options={'ordering': ['task', 'start']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['board']},
        ),
        migrations.AddField(
            model_name='task',
            name='reserved_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='handling',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 3, 14, 46, 44, 293982)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='handling',
            constraint=models.UniqueConstraint(fields=('task', 'editor', 'start'), name='unique_handling'),
        ),
    ]
