# Generated by Django 2.2.5 on 2019-10-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20191010_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='admin_mail',
            field=models.EmailField(blank=True, help_text='Your Mailadress. Will only be used to send you mails with links to frontend and backend.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='last_admin_mail_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
