# Generated by Django 3.0.2 on 2020-01-18 21:59

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_auto_20191010_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['created'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='handling',
            options={'ordering': ['task', 'start'], 'verbose_name': 'Handling', 'verbose_name_plural': 'Handlings'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['board'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='handling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasker_attachments', to='tasker.Handling', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='posted'),
        ),
        migrations.AlterField(
            model_name='board',
            name='admin_mail',
            field=models.EmailField(blank=True, help_text='Your Mailadress. Will only be used to send you mails with links to frontend and backend.', max_length=254, null=True, verbose_name='admin mail'),
        ),
        migrations.AlterField(
            model_name='board',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='tasker.Board', verbose_name='clones'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='board',
            name='label',
            field=models.CharField(max_length=100, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='board',
            name='last_admin_mail_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last time a mail to the admin was sent'),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='label', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='handling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasker_comments', to='tasker.Handling', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='posted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='handling',
            name='editor',
            field=models.CharField(max_length=30, verbose_name='editor'),
        ),
        migrations.AlterField(
            model_name='handling',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='handling',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='handling',
            name='success',
            field=models.BooleanField(blank=True, null=True, verbose_name='successfully'),
        ),
        migrations.AlterField(
            model_name='handling',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlings', to='tasker.Task', verbose_name='Handlings'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasker.Board', verbose_name='Tasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='tasker.Task', verbose_name='clones'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(max_length=100, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reserved_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='reserved by'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reserved_until',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='reserved until'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='label', unique_with=['board'], verbose_name='slug'),
        ),
    ]
