# Generated by Django 2.2.5 on 2019-10-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_auto_20191003_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handling',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
