# Generated by Django 3.0.2 on 2020-01-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_auto_20200118_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='tasker.Board', verbose_name='cloned_from'),
        ),
        migrations.AlterField(
            model_name='handling',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlings', to='tasker.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasker.Board', verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='tasker.Task', verbose_name='cloned from'),
        ),
    ]
