# Generated by Django 3.0.2 on 2020-01-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_auto_20200119_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='tasker.Task', verbose_name='requires'),
        ),
    ]
