# Generated by Django 3.0.2 on 2020-01-19 09:25

from django.db import migrations, models


def fill_admin_id(apps, schema_editor):
    Board = apps.get_model('tasker', 'Board')
    for board in Board.objects.filter(admin_id="_default"):
        board.admin_id = board.id
        board.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_task_requires'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='admin_id',
            field=models.CharField(default='_default', help_text='id used to authenticate for admin interface', max_length=30, verbose_name='admin id'),
            preserve_default=False,
        ),
        migrations.RunPython(fill_admin_id),
    ]
