# Generated by Django 3.0.4 on 2020-03-13 16:27

from django.db import migrations, models
import django.db.models.deletion


def fill_participants(apps, schema_editor):
    Participant = apps.get_model('tasker', 'Participant')
    participants = {}

    def _assure_nick(nick, board):
        if nick not in participants:
            p = Participant(nick=nick, board=board)
            p.save()
            participants[nick] = p.id
        return participants[nick]

    Handling = apps.get_model('tasker', 'Handling')
    for handling in Handling.objects.all():
        handling.editor = _assure_nick(handling.editor, handling.task.board)
        handling.save()

    Task = apps.get_model('tasker', 'Task')
    for task in Task.objects.all():
        if task.reserved_by:
            task.reserved_by = _assure_nick(task.reserved_by, task.board)
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0010_auto_20200121_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50, verbose_name='Nick')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tasker.Board', verbose_name='Board')),
            ],
        ),
        migrations.RunPython(fill_participants),
        migrations.AlterField(
            model_name='handling',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker.Participant'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasker.Participant'),
        ),
    ]
