# Generated by Django 3.0.4 on 2020-03-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0011_auto_20200313_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
    ]
