# Generated by Django 3.0.4 on 2020-03-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0012_auto_20200313_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='subscription_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('board', 'nick'), name='unique_nick'),
        ),
    ]
