# Generated by Django 5.2.7 on 2025-10-18 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0013_auto_20200314_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hide_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hide until'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_after',
            field=models.DurationField(blank=True, help_text='Never fully close this task, but automatically make it re-appear once the given duration passed after closing it.', null=True, verbose_name='repeat after'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='handling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tasker.handling', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='handling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tasker.handling', verbose_name='Notes'),
        ),
    ]
