# Generated by Django 5.2.7 on 2025-10-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0014_task_hide_until_task_repeat_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=100, help_text='Priority of this task: Tasks with higher priority will be shown before those with lower priority.', verbose_name='priority'),
        ),
    ]
