# Generated by Django 5.2.7 on 2025-10-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0015_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['board', '-priority'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
