# Generated by Django 5.2.7 on 2025-10-19 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0016_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasker.participant', verbose_name='reserved by'),
        ),
    ]
